using System.Text;

using FluentCommand.Generators.Models;

namespace FluentCommand.Generators;

public static class TypeAccessorWriter
{
    public static string Generate(EntityClass entityClass)
    {
        if (entityClass == null)
            throw new ArgumentNullException(nameof(entityClass));

        var codeBuilder = new IndentedStringBuilder();
        codeBuilder
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine();

        codeBuilder
            .Append("namespace ")
            .AppendLine(entityClass.EntityNamespace)
            .AppendLine("{")
            .IncrementIndent();

        WriteTypeAccessorClass(codeBuilder, entityClass);

        WriteRegistration(codeBuilder, entityClass);

        codeBuilder
            .DecrementIndent()
            .AppendLine("}"); // namespace

        return codeBuilder.ToString();
    }

    private static void WriteTypeAccessorClass(IndentedStringBuilder codeBuilder, EntityClass entity)
    {
        codeBuilder
            .Append("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"")
            .Append(ThisAssembly.Product)
            .Append("\", \"")
            .Append(ThisAssembly.InformationalVersion)
            .AppendLine("\")]")
            .Append("internal sealed class ")
            .Append(entity.EntityName)
            .AppendLine("GeneratedTypeAccessor : global::FluentCommand.Reflection.TypeAccessor")
            .AppendLine("{")
            .IncrementIndent();

        // static member accessor fields
        foreach (var prop in entity.Properties)
        {
            codeBuilder
                .Append("internal static readonly global::FluentCommand.Reflection.IMemberAccessor ")
                .Append(prop.PropertyName)
                .Append("Member = new ")
                .Append(prop.PropertyName)
                .AppendLine("MemberAccessor();");
        }

        codeBuilder.AppendLine();

        WriteConstructor(codeBuilder, entity);

        // nested member accessor classes
        foreach (var prop in entity.Properties)
        {
            WriteMemberAccessorClass(codeBuilder, entity, prop);
        }

        codeBuilder
            .DecrementIndent()
            .AppendLine("}") // class
            .AppendLine();
    }

    private static void WriteConstructor(IndentedStringBuilder codeBuilder, EntityClass entity)
    {
        codeBuilder
            .Append("public ")
            .Append(entity.EntityName)
            .AppendLine("GeneratedTypeAccessor()")
            .IncrementIndent()
            .Append(": base(")
            .Append("typeof(")
            .Append(entity.FullyQualified)
            .Append("), ");

        // TableName
        if (entity.TableName != null)
            codeBuilder.Append("\"").Append(entity.TableName).Append("\", ");
        else
            codeBuilder.Append("null, ");

        // TableSchema
        if (entity.TableSchema != null)
            codeBuilder.Append("\"").Append(entity.TableSchema).Append("\", ");
        else
            codeBuilder.Append("null, ");

        // Constructor func
        if (entity.InitializationMode == InitializationMode.ObjectInitializer)
            codeBuilder.Append("static () => new ").Append(entity.FullyQualified).Append("())");
        else
            codeBuilder.Append("null)");

        codeBuilder
            .AppendLine()
            .DecrementIndent();

        // Constructor body
        codeBuilder
            .AppendLine("{")
            .IncrementIndent();

        // Register members by property name
        foreach (var prop in entity.Properties)
        {
            codeBuilder
                .Append("RegisterMember(\"")
                .Append(prop.PropertyName)
                .Append("\", ")
                .Append(prop.PropertyName)
                .AppendLine("Member);");
        }

        // Register by column name where different from property name
        foreach (var prop in entity.Properties)
        {
            if (!string.Equals(prop.ColumnName, prop.PropertyName, StringComparison.Ordinal))
            {
                codeBuilder
                    .Append("RegisterMember(\"")
                    .Append(prop.ColumnName)
                    .Append("\", ")
                    .Append(prop.PropertyName)
                    .AppendLine("Member);");
            }
        }

        codeBuilder.AppendLine();

        // Register properties collection for default GetProperties() flags
        codeBuilder
            .AppendLine("RegisterProperties(")
            .IncrementIndent()
            .AppendLine("global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Instance,")
            .AppendLine("new global::FluentCommand.Reflection.IMemberAccessor[]")
            .AppendLine("{")
            .IncrementIndent();

        WritePropertyArray(codeBuilder, entity);

        codeBuilder
            .DecrementIndent()
            .AppendLine("});")
            .DecrementIndent();

        codeBuilder
            .DecrementIndent()
            .AppendLine("}") // constructor
            .AppendLine();
    }

    private static void WritePropertyArray(IndentedStringBuilder codeBuilder, EntityClass entity)
    {
        var index = 0;
        var count = entity.Properties.Count;

        foreach (var prop in entity.Properties)
        {
            codeBuilder.Append(prop.PropertyName).Append("Member");

            if (++index < count)
                codeBuilder.AppendLine(",");
            else
                codeBuilder.AppendLine();
        }
    }

    private static void WriteMemberAccessorClass(IndentedStringBuilder codeBuilder, EntityClass entity, EntityProperty prop)
    {
        codeBuilder
            .Append("private sealed class ")
            .Append(prop.PropertyName)
            .AppendLine("MemberAccessor : global::FluentCommand.Reflection.IMemberAccessor")
            .AppendLine("{")
            .IncrementIndent();

        // MemberType
        codeBuilder
            .Append("public global::System.Type MemberType => typeof(")
            .Append(prop.MemberTypeName)
            .AppendLine(");");

        // Name
        codeBuilder
            .Append("public string Name => \"")
            .Append(prop.PropertyName)
            .AppendLine("\";");

        // Column
        codeBuilder
            .Append("public string Column => \"")
            .Append(prop.ColumnName)
            .AppendLine("\";");

        // ColumnType
        if (prop.ColumnType != null)
            codeBuilder.Append("public string? ColumnType => \"").Append(prop.ColumnType).AppendLine("\";");
        else
            codeBuilder.AppendLine("public string? ColumnType => null;");

        // ColumnOrder
        if (prop.ColumnOrder.HasValue)
            codeBuilder.Append("public int? ColumnOrder => ").Append(prop.ColumnOrder.Value.ToString()).AppendLine(";");
        else
            codeBuilder.AppendLine("public int? ColumnOrder => null;");

        // Boolean metadata
        codeBuilder
            .Append("public bool IsKey => ")
            .AppendLine(prop.IsKey ? "true;" : "false;");

        codeBuilder
            .Append("public bool IsNotMapped => ")
            .AppendLine(prop.IsNotMapped ? "true;" : "false;");

        codeBuilder
            .Append("public bool IsDatabaseGenerated => ")
            .AppendLine(prop.IsDatabaseGenerated ? "true;" : "false;");

        codeBuilder
            .Append("public bool IsConcurrencyCheck => ")
            .AppendLine(prop.IsConcurrencyCheck ? "true;" : "false;");

        // ForeignKey
        if (prop.ForeignKey != null)
            codeBuilder.Append("public string? ForeignKey => \"").Append(prop.ForeignKey).AppendLine("\";");
        else
            codeBuilder.AppendLine("public string? ForeignKey => null;");

        codeBuilder
            .Append("public bool HasGetter => ")
            .AppendLine(prop.HasGetter ? "true;" : "false;");

        codeBuilder
            .Append("public bool HasSetter => ")
            .AppendLine(prop.HasSetter ? "true;" : "false;");

        codeBuilder
            .Append("public bool IsRequired => ")
            .AppendLine(prop.IsRequired ? "true;" : "false;");

        // DisplayName
        var displayName = prop.DisplayName ?? prop.PropertyName;
        codeBuilder
            .Append("public string DisplayName => \"")
            .Append(displayName)
            .AppendLine("\";");

        // DataFormatString
        if (prop.DataFormatString != null)
            codeBuilder.Append("public string? DataFormatString => \"").Append(prop.DataFormatString).AppendLine("\";");
        else
            codeBuilder.AppendLine("public string? DataFormatString => null;");

        codeBuilder.AppendLine();

        // GetValue
        if (prop.HasGetter)
        {
            codeBuilder
                .AppendLine("public object? GetValue(object instance)")
                .IncrementIndent()
                .Append("=> ((")
                .Append(entity.FullyQualified)
                .Append(")instance).")
                .Append(prop.PropertyName)
                .AppendLine(";")
                .DecrementIndent();
        }
        else
        {
            codeBuilder
                .AppendLine("public object? GetValue(object instance)")
                .IncrementIndent()
                .Append("=> throw new global::System.InvalidOperationException(\"Property '")
                .Append(prop.PropertyName)
                .AppendLine("' does not have a getter.\");")
                .DecrementIndent();
        }

        codeBuilder.AppendLine();

        // SetValue
        if (prop.HasSetter)
        {
            codeBuilder
                .AppendLine("public void SetValue(object instance, object? value)")
                .IncrementIndent()
                .Append("=> ((")
                .Append(entity.FullyQualified)
                .Append(")instance).")
                .Append(prop.PropertyName)
                .Append(" = (")
                .Append(prop.PropertyType)
                .AppendLine(")value!;")
                .DecrementIndent();
        }
        else
        {
            codeBuilder
                .AppendLine("public void SetValue(object instance, object? value)")
                .IncrementIndent()
                .Append("=> throw new global::System.InvalidOperationException(\"Property '")
                .Append(prop.PropertyName)
                .AppendLine("' does not have a setter.\");")
                .DecrementIndent();
        }

        codeBuilder
            .DecrementIndent()
            .AppendLine("}") // class
            .AppendLine();
    }

    private static void WriteRegistration(IndentedStringBuilder codeBuilder, EntityClass entity)
    {
        codeBuilder
            .Append("internal static class ")
            .Append(entity.EntityName)
            .AppendLine("TypeAccessorRegistration")
            .AppendLine("{")
            .IncrementIndent();

        using (codeBuilder.SuspendIndent())
            codeBuilder.AppendLine("#if NET5_0_OR_GREATER");

        codeBuilder.AppendLine("[global::System.Runtime.CompilerServices.ModuleInitializer]");

        using (codeBuilder.SuspendIndent())
            codeBuilder.AppendLine("#endif");

        codeBuilder
            .AppendLine("internal static void Register()")
            .AppendLine("{")
            .IncrementIndent()
            .AppendLine("global::FluentCommand.Reflection.TypeAccessor.Register(")
            .IncrementIndent()
            .Append("typeof(")
            .Append(entity.FullyQualified)
            .AppendLine("),")
            .Append("new ")
            .Append(entity.EntityName)
            .AppendLine("GeneratedTypeAccessor());")
            .DecrementIndent()
            .DecrementIndent()
            .AppendLine("}"); // method

        codeBuilder
            .DecrementIndent()
            .AppendLine("}"); // class
    }
}
