site_name: FluentCommand

repo_url: https://github.com/loresoft/FluentCommand

nav:
  - Home: index.md
  - Configuration: configuration.md
  - SQL Builder: sql.md
  - Parameters: parameter.md
  - Execute: execute.md
  - Queries: query.md
  - Caching: cache.md
  - Logging: logging.md
  - Generation: generation.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
