//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentCommand.SQLite.Tests.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlStatements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlStatements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluentCommand.SQLite.Tests.Data.SqlStatements", typeof(SqlStatements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Table [Priority] data
        ///INSERT INTO [Priority] ([Id],[Name],[Order],[Description],[CreatedDate],[ModifiedDate]) VALUES (1,&apos;High&apos;,1,&apos;A High Priority&apos;,&apos;2011-09-08 08:57:02&apos;,&apos;2011-09-08 08:57:02&apos;);
        ///INSERT INTO [Priority] ([Id],[Name],[Order],[Description],[CreatedDate],[ModifiedDate]) VALUES (2,&apos;Normal&apos;,2,&apos;A Normal Priority&apos;,&apos;2011-09-08 08:57:02&apos;,&apos;2011-09-08 08:57:02&apos;);
        ///INSERT INTO [Priority] ([Id],[Name],[Order],[Description],[CreatedDate],[ModifiedDate]) VALUES (3,&apos;Low&apos;,3,&apos;A Low Priority&apos;,&apos;2011-09-08 08: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrackerData {
            get {
                return ResourceManager.GetString("TrackerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS [Audit] (
        ///    [Id] integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///    [Date] datetime NOT NULL,
        ///    [UserId] int,
        ///    [TaskId] int,
        ///    [Content] varchar NOT NULL,
        ///    [Username] nvarchar(50) NOT NULL,
        ///    [CreatedDate] datetime NOT NULL,
        ///    CONSTRAINT [FK_Audit_Task] FOREIGN KEY ([TaskId]) REFERENCES [Task] ([Id])
        ///    CONSTRAINT [FK_Audit_User] FOREIGN KEY ([UserId]) REFERENCES [User] ([Id])
        ///);
        ///
        ///CREATE TABLE IF NOT EXISTS [Priority] (
        ///    [Id] int NOT NULL PRIMARY KEY, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrackerSchema {
            get {
                return ResourceManager.GetString("TrackerSchema", resourceCulture);
            }
        }
    }
}
